version: '3.8'

services:
  # XÓA: Toàn bộ service 'db' đã bị xóa khỏi đây.
  # XÓA: Toàn bộ service 'redis' đã bị xóa khỏi đây.

  # --- KAFKA SETUP ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    networks:
      - ecommerce-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka_broker
    networks:
      - ecommerce-net
    depends_on:
      - zookeeper
    ports:
      # Port 9092 để các ứng dụng bên ngoài Docker (trên máy host) có thể kết nối
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      # Listener cho kết nối từ BÊN TRONG Docker (qua service name 'kafka')
      # Listener cho kết nối từ BÊN NGOÀI Docker (qua localhost)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:29092,PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest # SỬA LỖI: Tên image chính xác
    container_name: kafka_ui
    depends_on:
      - kafka
    ports:
      # Map cổng 8080 của container sang 8090 của máy host để tránh xung đột
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092 # Kết nối tới Kafka qua mạng nội bộ
    networks:
      - ecommerce-net
  # --- END KAFKA SETUP ---

  mainecommerce:
    build:
      context: .
      dockerfile: MainEcommerceService/Dockerfile
    container_name: main_ecommerce_service
    ports:
      - "5166:8080"
    depends_on:
      - kafka # SỬA: Xóa 'db' và 'redis' khỏi depends_on
    environment:
      - GatewayBaseUrl=${GATEWAY_BASE_URL}
      # SỬA: Sử dụng biến môi trường cho connection string mới
      - ConnectionStrings__MainDbService=${EXTERNAL_DB_CONNECTION}
      - ConnectionStrings__RedisConnection=${EXTERNAL_REDIS_CONNECTION}
      - Kafka__BootstrapServers=kafka:29092
      - jwt__Secret-Key=${JWT_SECRET_KEY}
      - jwt__Issuer=${JWT_ISSUER}
      - jwt__Audience=${JWT_AUDIENCE}
      - ASPNETCORE_ENVIRONMENT=Development
      
    networks:
      - ecommerce-net

  productservice:
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    container_name: product_service
    ports:
      - "5079:8080"
    depends_on:
      - kafka # SỬA: Xóa 'db' và 'redis' khỏi depends_on
    environment:
      # SỬA: Sử dụng biến môi trường cho connection string mới
      - ConnectionStrings__ProductDbService=${EXTERNAL_PRODUCT_DB_CONNECTION}
      - ConnectionStrings__RedisConnection=${EXTERNAL_REDIS_CONNECTION}
      - Kafka__BootstrapServers=kafka:29092
      - AWS__AccessKey=${AWS_ACCESS_KEY}
      - AWS__SecretKey=${AWS_SECRET_KEY}
      - AWS__Region=us-east-1
      - AWS__BucketName=ecommerce231
      - jwt__Secret-Key=${JWT_SECRET_KEY}
      - jwt__Issuer=${JWT_ISSUER}
      - jwt__Audience=${JWT_AUDIENCE}
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - ecommerce-net

  gateway:
    build:
      context: .
      dockerfile: GateWayService/Dockerfile
    container_name: gateway_service
    ports:
      - "5282:8080"
    depends_on:
      - mainecommerce
      - productservice
    environment:
      # Đảm bảo dòng này tồn tại và chính xác
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - ecommerce-net

  blazorapp:
    build:
      context: .
      dockerfile: BlazorWebApp/Dockerfile
    container_name: blazor_webapp
    ports:
      - "5093:8080"
    depends_on:
      - gateway
    environment:
      # 🔥 SỬA: Sử dụng biến môi trường từ .env
      - GatewayBaseUrl=${GATEWAY_BASE_URL}
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
      # Email Settings
      - EmailSettings__SmtpHost=${EMAIL_SMTP_HOST}
      - EmailSettings__SmtpPort=${EMAIL_SMTP_PORT}
      - EmailSettings__FromEmail=${EMAIL_FROM_EMAIL}
      - EmailSettings__Username=${EMAIL_USERNAME}
      - EmailSettings__Password=${EMAIL_PASSWORD}
      # JWT Settings
      - jwt__Secret-Key=${JWT_SECRET_KEY}
      - jwt__Issuer=${JWT_ISSUER}
      - jwt__Audience=${JWT_AUDIENCE}
      # App Settings
      - AppSettings__BaseUrl=${APP_BASE_URL}
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge